---
title: "regression"
author: "Yuki Hirayama"
date: "2023-05-19"
output: html_document
---

```{r}
# Data Wrangling

library(tidyverse)
library(tseries)
library(leaps)
library(lubridate)
library(forecast)
path <- "C:\\Users\\y1u0u\\Documents\\R\\2223_3_spring\\01_TS\\fp"
df <- read_csv(file.path(path, 'finalData.csv'))

# drop unnecessary variables
df_base <- df %>% select(-feelslikemax,
                        -feelslikemin,
                        -feelslike,
                        -name,
                        -conditions,
                        -description,
                        -stations,
                        -sunset,
                        -sunrise,
                        -datetime,
                        -sunrise,
                        -sunset,
                        -preciptype,
                        -icon,
                        -datetime,
                        -avgTemp,
                        -precipprob,
                        -severerisk)

df_base$temp <- df_base$temp + 50
df_base$tempmax <- df_base$tempmax + 50
df_base$tempmin <- df_base$tempmin + 50
```

# temp

```{r}
df_reg <- df_base %>% select(-tempmax, -tempmin)

df_reg$windgust <- ifelse(is.na(df_reg$windgust), 0, df_reg$windgust)
#df_reg$severerisk <- ifelse(is.na(df_reg$severerisk), 0, df_reg$severerisk)

df_reg_ts <- ts(df_reg, start = c(2012, 121.25), frequency = 365.25)

# Box Cox
df_reg_ts_bc <- df_reg_ts
df_reg_ts_bc[,"temp"] <- BoxCox(df_reg_ts[,"temp"], lambda = 2)

# split
train_ts <- window(df_reg_ts_bc, start = c(2012, 121.25), end = c(2021, 120))
test_ts <- window(df_reg_ts_bc, start = c(2021, 121))

train_ts_2 <- window(df_reg_ts, start = c(2012, 121.25), end = c(2021, 120))
test_ts_2 <- window(df_reg_ts, start = c(2021, 121))
```


```{r}
# forward stepwise
regfit <- regsubsets(temp ~.,
                     data = train_ts,
                     nvmax = 16,
                     method = "forward")
summary(regfit)
```

```{r}
# check error using test data
test.mat <- model.matrix(temp ~., data = as.data.frame(test_ts))

val.error <- rep(NA, 16)
for (i in 1:16) {
  coefi = coef(regfit, id = i)
  pred = test.mat[, names(coefi)]%*%coefi
  val.error[i] = mean((test_ts[, "temp"] - pred)^2)
}
val.error

coef(regfit, which.min(val.error))
```

```{r}
# best model (p = 7)
bestfit <- tslm(temp ~ dew + humidity + snowdepth +
                  winddir + sealevelpressure + 
                  cloudcover + visibility,
                data = train_ts_2,
                lambda = 2)

summary(bestfit)
```

```{r}
# residual
checkresiduals(bestfit)
```

- Need to do regression with ARIMA errors.

```{r}
xreg <- cbind(dew = train_ts_2[, "dew"],
              humidity = train_ts_2[, "humidity"],
              snowdepth = train_ts_2[, "snowdepth"],
              winddir = train_ts_2[, "winddir"],
              sealevelpressure = train_ts_2[, "sealevelpressure"],
              cloudcover = train_ts_2[, "cloudcover"],
              visibility = train_ts_2[, "visibility"])

reg_w_arima <- auto.arima(train_ts_2[, "temp"],
                          lambda = 2,
                          xreg = xreg)

summary(reg_w_arima)
checkresiduals(reg_w_arima)
```

```{r}
newxreg <- cbind(dew = test_ts_2[, "dew"],
              humidity = test_ts_2[, "humidity"],
              snowdepth = test_ts_2[, "snowdepth"],
              winddir = test_ts_2[, "winddir"],
              sealevelpressure = test_ts_2[, "sealevelpressure"],
              cloudcover = test_ts_2[, "cloudcover"],
              visibility = test_ts_2[, "visibility"])
fcast <- forecast(reg_w_arima, xreg = newxreg)
fcast[["mean"]] <- fcast[["mean"]] - 50
fcast[["lower"]] <- fcast[["lower"]] - 50
fcast[["upper"]] <- fcast[["upper"]] - 50
fcast[["x"]] <- fcast[["x"]] - 50
fcast[["fitted"]] <- fcast[["fitted"]] - 50
plot(fcast,
     ylim = c(-30, 30))
```

```{r}
test_ts_2_true <- test_ts_2[, "temp"] - 50
test_ts_2_true
accuracy(fcast, test_ts_2_true)
```